### ISSUE TITLE
Full keyboard control

### ISSUE THREAD

**Issue by yvesio** [distantnative/multiselect#14]
We use this plugin preferably for very long option list. It would be nice to make the options selectable after a search is performed. So the ideal workflow would be

* tab into the multiselect field
* enter a search phrase
* once the desired item is in view navigate with the down / up arrows and select it with return
* move out of the multiselect field with another tab key press

**Comment by distantnative** [comment]
Totally agree and like the idea. Will see if/when I find the time to implement it.

**Comment by distantnative** [comment]
Just added it to the develop branch. It will need a little more refinement, but will be included in the next release shortly.
