### ISSUE TITLE
CheckboxesField not found

### ISSUE THREAD

**Issue by lukehatfield** [distantnative/multiselect#15]
I assume I'm doing something wrong as I get this error after installation:
`Fatal error: Class 'CheckboxesField' not found in /Users/luke/.../site/plugins/multiselect/multiselect.php on line 3` Just don't know what it is! 

I installed it as a git submodule with this command: 
`git submodule add git@github.com:distantnative/multiselect.git site/plugins/multiselect`

Thanks for any help.

**Comment by samnabi** [comment]
Is your `kirby/toolkit` folder empty?

**Comment by lukehatfield** [comment]
No, I have these in there:
<img width="144" alt="screenshot 2016-03-16 15 09 37" src="https://cloud.githubusercontent.com/assets/5399943/13825543/627108a4-eb89-11e5-9d35-00f3056105a8.png">

**Comment by lukehatfield** [comment]
Oops. I had placed this field plugin in the plugin folder, not the fields folder. No error now! Thanks.
